Module3
amelenas/Module3 pull request #1
Opened 2022-05-11 11:32 UTC by amelenas

2022-05-12 14:25 UTC, baffaonline reviewed
Выделил основные вопросы

2022-05-12 14:25 UTC, baffaonline commented on model/src/main/java/com/epam/esm/dao/CertificateDao.java
> +    long findSize();
findSize() метод можно было в общий интерфейс вынести

2022-05-12 14:25 UTC, baffaonline commented on model/src/main/java/com/epam/esm/dao/entity/Tag.java
> +    @JsonIgnore
Почему здесь стоит @JsonIgnore?

2022-05-12 14:25 UTC, baffaonline commented on model/src/main/java/com/epam/esm/dao/entity/User.java
> +    @Column(name = "lock_user")
А что это за lock?

2022-05-12 14:25 UTC, baffaonline commented on model/src/main/java/com/epam/esm/dao/impl/UserDaoImpl.java
> +        Session session = sessionFactory.openSession();
Ты используешь @Transactional, все методы автоматически будут работать в транзакции, так что нет смысла дополнительно делать свою транзакцию

2022-05-12 14:25 UTC, baffaonline commented on service/src/main/java/com/epam/esm/service/impl/CertificateServiceImpl.java
> +        if (result.isPresent()) {
Здесь можно использовать orElseThrow

2022-05-12 14:25 UTC, baffaonline commented on service/src/main/java/com/epam/esm/service/impl/CertificateServiceImpl.java
> +        if (updates.size() < 1) {
Можно использовать isEmpty?

2022-05-12 14:25 UTC, baffaonline commented on service/src/main/java/com/epam/esm/service/impl/CertificateServiceImpl.java
> +        if (updates.containsKey(NAME)){
Валидации занимают слишком много в методе, лучше их вынести в отдельный метод

2022-05-12 14:25 UTC, baffaonline commented on web/src/main/java/com/epam/esm/controller/CertificateController.java
> +    private CollectionModel<CertificateDto> getCollectionModelWithPagination(int page, int limit, List<CertificateDto> list) {
Эти методы можно вынести из контроллера

2022-05-12 14:25 UTC, baffaonline commented on web/src/main/java/com/epam/esm/controller/config/CommonConfig.java
> +        ModelMapper modelMapper = new ModelMapper();
Для чего этот ModelMapper используется?

2022-05-12 14:25 UTC, baffaonline commented on web/src/main/java/com/epam/esm/controller/OrderController.java
> +        List<OrderDto> list = orderService.findAll(skipQuantity(page, size), size).stream().map(orderDtoConverter::convertToDto).collect(Collectors.toList());
Конвертация в DTO должна быть на уровне сервиса

2022-05-13 07:10 UTC, Restonov requested changes

2022-05-13 07:10 UTC, maxplyushko commented on logging/src/main/java/com/epam/esm/logging/LoggingConfig.java
> +public class LoggingConfig {
It will be right to move it to 'config' package since it's config and place here LoggingAspect

2022-05-13 07:10 UTC, maxplyushko commented on model/src/main/java/com/epam/esm/dao/impl/CertificateDaoImpl.java
> +@Repository
Why u don't place @Transactional here as well?

2022-05-13 07:10 UTC, maxplyushko commented on service/src/main/java/com/epam/esm/service/UserService.java
> +    Long findSize();
same as for DAO, move this duplicated method to separate Interface

2022-05-13 07:10 UTC, maxplyushko commented on service/src/main/java/com/epam/esm/service/impl/CertificateServiceImpl.java
> +        if (updates.containsKey(NAME)){
and why do you put one 'if' under another 'if'? you can just combine them like 
`updates.containsKey(NAME) && !Validator.validateName(updates.get(NAME).toString(), exceptionHandler)`
Install SonarLint plugin so you will see issues like this

2022-05-13 07:10 UTC, Restonov commented on service/src/main/java/com/epam/esm/service/impl/CertificateServiceImpl.java
> +        ExceptionHandler exceptionHandler = new ExceptionHandler();
Come on. We are writing code with Spring. Use DI here

2022-05-13 07:10 UTC, Restonov commented on web/src/main/resources/application.properties
> +spring.second-datasource.password=12345
It's forbidden to store any sensitive info (e.q. passwords, tokens) in public storage

2022-05-13 07:10 UTC, Restonov commented on web/src/main/resources/messages.properties
> +
What's the difference between this file and messages_en ?

2022-05-13 13:21 UTC, merged